/**
 * Sends the generated newsletter to a specific subscriber using GmailApp.
 * 
 * @param {String} email - Subscriber's email address
 * @param {String} name - Subscriber's name (optional)
 * @param {String} unsubscribeToken - Unique token for the unsubscribe link
 * @param {String} newsletterContent - The raw HTML generated by Gemini
 */
function sendEmail(email, name, unsubscribeToken, newsletterContent) {
  var subject = "🚀 Your AI Weekly Digest is Here!";
  var recipientName = name ? name : "AI Enthusiast";
  
  // Construct the Unsubscribe Link (using ScriptApp to get the current Web App URL dynamically)
  // Note: ScriptApp.getService().getUrl() only works if deployed as a Web App
  var webAppUrl = ScriptApp.getService().getUrl();
  var unsubscribeLink = webAppUrl + "?action=unsubscribe&token=" + unsubscribeToken;

  var htmlBody = getEmailTemplate(recipientName, newsletterContent, unsubscribeLink);

  GmailApp.sendEmail(email, subject, "", {
    name: "Muhammad Bilal AI Digest",
    htmlBody: htmlBody,
    replyTo: "no-reply@" + email.split('@')[1] // Optional: set a no-reply address
  });
}

/**
 * Wraps the Gemini-generated content in a professional, responsive HTML email template.
 * Matches the dark, modern aesthetic of the portfolio.
 * 
 * @param {String} name - Recipient's name
 * @param {String} content - The HTML content from Gemini
 * @param {String} unsubscribeLink - The generated unsubscribe URL
 * @returns {String} The full HTML string ready for email clients
 */
function getEmailTemplate(name, content, unsubscribeLink) {
  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      body {
        margin: 0;
        padding: 0;
        background-color: #060b19; /* Matches portfolio background */
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #ccd6f6;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        background-color: #112240;
        border-radius: 8px;
        overflow: hidden;
      }
      .header {
        background-color: #060b19;
        padding: 30px 20px;
        text-align: center;
        border-bottom: 2px solid #64ffda;
      }
      .header h1 {
        color: #c8f04a;
        margin: 0;
        font-size: 24px;
        letter-spacing: 1px;
      }
      .content {
        padding: 30px;
        line-height: 1.6;
        font-size: 16px;
      }
      .content h2 {
        color: #64ffda;
        font-size: 20px;
        margin-top: 30px;
      }
      .content h3 {
        color: #e6f1ff;
        font-size: 18px;
      }
      .content a {
        color: #64ffda;
        text-decoration: none;
      }
      .content a:hover {
        text-decoration: underline;
      }
      .footer {
        background-color: #060b19;
        padding: 20px;
        text-align: center;
        font-size: 12px;
        color: #8892b0;
      }
      .footer a {
        color: #8892b0;
        text-decoration: underline;
      }
      .btn {
        display: inline-block;
        padding: 10px 20px;
        margin-top: 20px;
        background-color: transparent;
        color: #64ffda;
        border: 1px solid #64ffda;
        border-radius: 4px;
        text-decoration: none;
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #060b19; padding: 20px 0;">
      <tr>
        <td align="center">
          <div class="container">
            <!-- Header -->
            <div class="header">
              <h1>AI WEEKLY DIGEST 🤖</h1>
            </div>
            
            <!-- Body Content -->
            <div class="content">
              <p>Hi ${name},</p>
              
              <!-- Gemini Content Injected Here -->
              ${content}
              
              <br><br>
              <p>Stay curious,</p>
              <p><strong>Muhammad Bilal</strong></p>
            </div>
            
            <!-- Footer -->
            <div class="footer">
              <p>You are receiving this because you subscribed on my portfolio.</p>
              <p><a href="${unsubscribeLink}">Unsubscribe here</a> if you no longer wish to receive these emails.</p>
            </div>
          </div>
        </td>
      </tr>
    </table>
  </body>
  </html>
  `;
}
