/**
 * Sends the generated newsletter to a specific subscriber using GmailApp.
 * 
 * @param {String} email - Subscriber's email address
 * @param {String} name - Subscriber's name (optional)
 * @param {String} unsubscribeToken - Unique token for the unsubscribe link
 * @param {String} newsletterContent - The raw HTML generated by Gemini
 */
function sendEmail(email, name, unsubscribeToken, newsletterContent) {
  var subject = "🚀 Your AI Weekly Digest is Here!";
  var recipientName = name ? name : "AI Enthusiast";
  
  // Construct the Unsubscribe Link (using ScriptApp to get the current Web App URL dynamically)
  // Note: ScriptApp.getService().getUrl() only works if deployed as a Web App
  var webAppUrl = ScriptApp.getService().getUrl();
  var unsubscribeLink = webAppUrl + "?action=unsubscribe&token=" + unsubscribeToken;

  var htmlBody = getEmailTemplate(recipientName, newsletterContent, unsubscribeLink);

  GmailApp.sendEmail(email, subject, "", {
    name: "Muhammad Bilal AI Digest",
    htmlBody: htmlBody,
    replyTo: "no-reply@" + email.split('@')[1] // Optional: set a no-reply address
  });
}

/**
 * Wraps the Gemini-generated content in a professional, responsive HTML email template.
 * Matches the dark, modern aesthetic of the portfolio.
 * 
 * @param {String} name - Recipient's name
 * @param {String} content - The HTML content from Gemini
 * @param {String} unsubscribeLink - The generated unsubscribe URL
 * @returns {String} The full HTML string ready for email clients
 */
function getEmailTemplate(name, content, unsubscribeLink) {
  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      body {
        margin: 0;
        padding: 0;
        background-color: #05080f;
        font-family: 'Outfit', 'Roboto', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #d1e2fc;
      }
      .container {
        max-width: 600px;
        margin: 0 auto;
        background-color: #0a0d16;
        border-radius: 16px;
        border: 1px solid rgba(102, 255, 213, 0.15);
        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
        overflow: hidden;
      }
      .header {
        background: linear-gradient(135deg, #05080f 0%, #0a0d16 100%);
        padding: 40px 20px;
        text-align: center;
        border-bottom: 2px solid #66ffd5;
      }
      .header h1 {
        color: #d1e2fc;
        margin: 0;
        font-size: 28px;
        font-weight: 700;
        letter-spacing: 2px;
        text-transform: uppercase;
      }
      .header .highlight {
        color: #66ffd5;
      }
      .content {
        padding: 40px;
        line-height: 1.8;
        font-size: 16px;
        color: #9aa3ba;
      }
      .content h2 {
        color: #ab73fa;
        font-size: 22px;
        margin-top: 35px;
        margin-bottom: 15px;
        font-weight: 600;
      }
      .content h3 {
        color: #d1e2fc;
        font-size: 18px;
        margin-top: 25px;
      }
      .content p {
        margin-bottom: 16px;
      }
      .content a {
        color: #66ffd5;
        text-decoration: none;
        border-bottom: 1px dashed #66ffd5;
        transition: all 0.3s ease;
      }
      .content a:hover {
        color: #ab73fa;
        border-bottom-color: #ab73fa;
      }
      .footer {
        background-color: #05080f;
        padding: 30px;
        text-align: center;
        font-size: 13px;
        color: #9aa3ba;
        border-top: 1px solid rgba(255, 255, 255, 0.05);
      }
      .footer a {
        color: #66ffd5;
        text-decoration: none;
      }
      .btn {
        display: inline-block;
        padding: 12px 24px;
        margin-top: 25px;
        background-color: rgba(102, 255, 213, 0.1);
        color: #66ffd5 !important;
        border: 1px solid #66ffd5;
        border-radius: 8px;
        text-decoration: none !important;
        font-weight: 600;
        letter-spacing: 1px;
      }
      .greeting {
        font-size: 20px;
        color: #d1e2fc;
        font-weight: 600;
        margin-bottom: 25px;
      }
      .signoff {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid rgba(255, 255, 255, 0.05);
      }
      .signoff strong {
        color: #d1e2fc;
        font-size: 18px;
      }
    </style>
  </head>
  <body>
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #05080f; padding: 40px 0;">
      <tr>
        <td align="center">
          <div class="container">
            <!-- Header -->
            <div class="header">
              <h1>AI WEEKLY <span class="highlight">DIGEST</span></h1>
            </div>
            
            <!-- Body Content -->
            <div class="content">
              <div class="greeting">Hi ${name},</div>
              
              <!-- Gemini Content Injected Here -->
              ${content}
              
              <div class="signoff">
                <p>Stay curious & ahead of the curve,</p>
                <p><strong>Muhammad Bilal</strong></p>
              </div>
            </div>
            
            <!-- Footer -->
            <div class="footer">
              <p>You are receiving this premium digest because you subscribed via my portfolio.</p>
              <p style="margin-top: 15px;">
                <a href="${unsubscribeLink}">Unsubscribe securely</a>
              </p>
            </div>
          </div>
        </td>
      </tr>
    </table>
  </body>
  </html>
  `;
}
